server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: article
          uri: lb://ARTICLE
          predicates:
            - Path=/api/v1/articles/**
        - id: comment
          uri: lb://COMMENT
          predicates:
            - Path=/api/v1/comments/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false